--[[ ctrl - DB.lua - t@wse.nyc - 8/17/24 ]] --


---@class ctrl
local ctrl = select(2, ...)
local c, s, a = ctrl.c, ctrl.s, ctrl.a

_G.CtrlDB = {

    -- Test

    [104091] = {
        t1 = s.tits..' Dem titties',
        t2 = s.crit .. ' Imposter!',
        t3 = '㏈ Lingerie',
        color = c.o,
        symbol = s.d20,
        debug = '104091',
    },
    [185562] = {
        t1 = s.tits..' Dem titties',
        t2 = s.crit .. ' Imposter!',
        t3 = '㏈ Lingerie',
        color = c.o,
        symbol = s.d20,
        debug = '104091',
    },

    --Necrotic Wake

    [165137] = { --Zolramus Gatekeeper
        t1 = s.cock .. " Solo Pull",
        t2 = s.infinite .. " Spawns adds from Portal",
        t3 = s.wand .. ' Dispel Clinging Darkness',
        color = c.y,
        symbol = s.warn,
        debug = '323347',
    },
    [166302] = { --Corpse Harvester
        t1 = s.kick2 .. " Prio Kick Drain Fluids",
        t2 = "",
        t3 = '',
        color = c.o,
        symbol = s.kick,
        debug = '334748',
    },
    [163121] = { --Stitched Vanguard
        t1 = s.focus .. " Focus Down",
        t2 = s.warn .. " Stacking Enrage",
        t3 = '',
        color = c.o,
        symbol = s.target,
        debug = '320703',
    },
    [166880] = { --Blightbone BOSS
        t1 = '󱟂 Tank against walls for Fetid Gas',
        t2 = s.pullback .. '󰁌 Bait Retch back, others run out',
        t3 = s.serpentine .. ' Kite Worms, others focus. Causes Gas.',
        color = c.p,
        symbol = s.tankwarn,
        debug = '320596, 320637',
    },
    [163618] = { --Zolramus Necromancer
        t1 = s.nuke .. ' Nuke - Ignore skeletons',
        t2 = s.kick .. ' Kick Necrotic Bolt',
        t3 = s.bubble .. ' (Healing absorb)',
        color = c.y,
        symbol = s.focus,
        debug = '320462',
    },
    [165919] = { --Skeletal Marauder
        t1 = s.turnaround .. ' Point Cleave Away',
        t2 = s.kick .. ' Prio Kick Rasping Scream',
        t3 = '',
        color = c.o,
        symbol = s.turnmob,
        debug = '324293',
    },
    [165824] = { --Nar'zudah Miniboss
        t1 = s.bubble .. ' Dark Shroud: Purge/Arcane Torrent',
        t2 = s.sixfeet .. ' Shared Agony: Run 25yds',
        t3 = s.kick .. ' Kick Necrotic Bolt',
        color = c.r,
        symbol = s.warn,
        debug = '335141, 327399, 320462',
    },
    [163128] = { --Zolramus Sorcerer
        t1 = s.one .. ' Kill first',
        t2 = s.kick .. ' Kick Necrotic Bolt',
        t3 = '',
        color = c.o,
        symbol = s.one,
        debug = '320462',
    },
    [163619] = { --Zolramus Bonecarver
        t1 = s.two .. ' Kill second',
        t2 = s.kick .. ' Kick Boneflay',
        t3 = s.bleed .. ' Bleed, health reduction',
        color = c.y,
        symbol = s.two,
        debug = '321807',
    },
    [165197] = { --Skeletal Monstrosity Miniboss
        t1 = '󰁄 Pulls in then Cleaves',
        t2 = '󰚮 Movement speed debuff',
        t3 = s.tankwarn .. ' High tank damage',
        color = c.r,
        symbol = s.tankwarn,
        debug = '324372, 324381',
    },
    [163157] = { --Amarth BOSS
        t1 = s.nuclear .. ' Nuke adds before Final Harvest',
        t2 = s.puddle .. " Don't stand on summon",
        t3 = '󰁌 Dodge Breath, ' .. s.wand .. ' Soothe Frenzy, ' .. s.kick .. ' Kick Bolt',
        color = c.p,
        symbol = s.fallout,
        debug = '321247, 333493, 321226, 333633',
    },
    [173016] = { --Corpse Collector
        t1 = s.kick .. ' Prio Kick Drain Fluids',
        t2 = s.kick2 .. ' Kick Goresplatter',
        t3 = '',
        color = c.o,
        symbol = s.focus,
        debug = '334748, 338353',
    },
    [172981] = { --Kyrian Stitchwerk
        t1 = s.heal .. ' Stacking Tank Debuff',
        t2 = '',
        t3 = '',
        color = c.y,
        symbol = s.tankstar,
        debug = '338357',
    },
    [165872] = { --Flesh Crafter
        t1 = '󱡂 Point Cleaver at enemies!',
        t2 = s.kick .. ' Kick Repair Flesh',
        t3 = '',
        color = c.g,
        symbol = s.rotate,
        debug = '323496, 327130',
    },
    [166266] = { --Spare Parts
        t1 = '󱄶 Fixates',
        t2 = '',
        t3 = '',
        color = c.b,
        symbol = s.donttank,
        debug = '',
    },
    [173044] = { --Stitching Assistant
        t1 = '󱡂 Point Cleaver at Separation!',
        t2 = s.kick .. ' Kick Drain Fluids',
        t3 = '',
        color = c.o,
        symbol = s.rotate,
        debug = '323496, 334748',
    },
    [167731] = { --Separation Assistant
        t1 = '󱡂 Point Cleaver at Stitching!',
        t2 = '󱄶 8s Fixate',
        t3 = '',
        color = c.y,
        symbol = s.focus,
        debug = '323496, 338606',
    },
    [163621] = { --Goregrind
        t1 = s.heal .. ' Stacking Tank Debuff',
        t2 = s.bleed .. ' 12s Bleed',
        t3 = s.tankwarn .. ' High tank damage',
        color = c.r,
        symbol = s.tankwarn,
        debug = '338357, 338456, 333477',
    },
    [163622] = { --Goregrind Bits
        t1 = s.heal .. ' Leap',
        t2 = '',
        t3 = '',
        color = c.w,
        symbol = s.bunny,
        debug = '338022',
    },
    [163620] = { --Rotspew
        t1 = s.mushroom .. 'Disease Cloud',
        t2 = '',
        t3 = '',
        color = c.y,
        symbol = s.poop,
        debug = '333485',
    },
    [163623] = { --Rotspew Leftovers
        t1 = s.heal .. ' Leap',
        t2 = '',
        t3 = '',
        color = c.w,
        symbol = s.bunny,
        debug = '338022',
    },
    [166882] = { --Surgeon Stitchflesh Boss
        t1 = s.hand .. ' Hold CDs',
        t2 = '󰆷 Point Meat Hook at stage',
        t3 = s.nuke .. ' Pop CDs, Burn',
        color = c.c,
        symbol = s.hand,
        debug = '338022',
    },
    [164578] = { --Creation
        t1 = '󰆷 Point Meat Hook at stage',
        t2 = s.mushroom .. ' Mutilate, Rot',
        t3 = '',
        color = c.p,
        symbol = s.point,
        debug = '322681, 320376, 334321',
    },
    [162693] = { --Nalthor
        t1 = s.puddle .. ' Frozen 12s: everyone out, Dispel',
        t2 = s.nuke .. ' Comet Storm 5s: kite out-and-back',
        t3 = s.run .. ' Dark Exile: Run to corner on return!',
        color = c.c,
        symbol = s.frost,
        debug = '320788, 320784, 321894',
    },


    -- Mists

    [164920] = { --Drust Soulcleaver
        t1 = '󰁨 Dispel Tank Debuff',
        t2 = '',
        t3 = '',
        color = c.g,
        symbol = s.heal,
        debug = '322557',
    },
    [164921] = { --Drust Harvester
        t1 = s.kick2 .. ' Kick Channel',
        t2 = '',
        t3 = '',
        color = c.y,
        symbol = s.kick,
        debug = '322938',
    },
    [164929] = { --Tirnenn Villager
        t1 = 'ぁ Dodge Frontal',
        t2 = 'ㄫ Melee Stack',
        t3 = '䆳 Cleave Overgrowth',
        color = c.o,
        symbol = s.turnmob,
        debug = '321968, 322486',
    },
    [164926] = { --Drust Boughbreaker
        t1 = '䅭 @50%: 6s Thrash Dmg',
        t2 = '󰌺 One-at-a-time!',
        t3 = '󰿅 Run out of swirly',
        color = c.o,
        symbol = s.desync,
        debug = '324909, 324923',
    },
    [164567] = { --Ingra Maloch - BOSS1
        t1 = '㍊ Shielded',
        t2 = '䂺 12s Nuke when active',
        t3 = '㏅ Kick Spirit Bolt',
        color = c.c,
        symbol = s.two,
        debug = '321006, 323057',
    },
    [164804] = { --Droman Oulfarran - BOSS2
        t1 = '󰯐 Focus until 20%',
        t2 = '䅧 Dodge Frontal',
        t3 = '󰿅 Swirlies, あ Fear',
        color = c.p,
        symbol = s.one,
        debug = '323137, 323177, 328756',
    },
    [166299] = { --Mistveil Tender
        t1 = '㏅ Prio Kick Heal',
        t2 = '',
        t3 = '',
        color = c.y,
        symbol = s.kick,
        debug = '324914',
    },
    [166275] = { --Mistveil Shaper
        t1 = '㏅ Prio Kick Shield',
        t2 = '',
        t3 = '',
        color = c.o,
        symbol = s.kick2,
        debug = '324776',
    },
    [166304] = { --Mistveil Stinger
        t1 = '󰁨 Dispel Anima Injection',
        t2 = 'ㆫ within 6s or explodes',
        t3 = '󰁄 Melee stack for charge',
        color = c.g,
        symbol = s.heal,
        debug = '325223',
    },
    [173714] = { --Mistveil Nightblossom
        t1 = '󰋠 Dispel Tank Poison',
        t2 = '㍋ 3 Stacks',
        t3 = '󱊝 High Damage',
        color = c.r,
        symbol = s.skull,
        debug = '340288',
    },
    [173720] = { --Mistveil Gorgegullet
        t1 = '㎗ Spread for Leap',
        t2 = '㎔ 12y radius: 18s Poison',
        t3 = '󰚮 12y cone: 8s Slow',
        color = c.g,
        symbol = s.spread,
        debug = '340305, 340304, 340300',
    },
    [173655] = { --Mistveil Matriarch
        t1 = '󰿅 Drag out of Pool',
        t2 = 'ぁ Dodge Cone',
        t3 = '',
        color = c.y,
        symbol = s.getout,
        debug = '340189, 340160',
    },
    [170217] = { --Mistcaller BOSS1
        t1 = '㏆ Tank Kick Patty Cake',
        t2 = 'ぁ Dodge Ball',
        t3 = '㇂ Vulpin',
        color = c.p,
        symbol = s.kick,
        debug = '321828, 321834, 165251',
    },
    [171772] = { --Mistveil Defender
        t1 = '󰎔 Drag out of Mist Ward',
        t2 = '󰎔 Spread for Charge',
        t3 = '䆳 Cleave, Enrage, Aura',
        color = c.o,
        symbol = s.turnmob,
        debug = '463236, 463248, 324736',
    },
    [166276] = { --Mistveil Guardian
        t1 = '󰎔 Anima Slash stacking debuff',
        t2 = '󱟂 Roots, knockbacks, flurry',
        t3 = '',
        color = c.y,
        symbol = s.turnmob,
        debug = '463217',
    },
    [167111] = { --Spinemaw Staghorn
        t1 = '㏆ Prio Kick Resistance',
        t2 = '㏆ Prio Kick Regeneration',
        t3 = '',
        color = c.r,
        symbol = s.kick,
        debug = '326046, 340544',
    },
    [167113] = { --Spinemaw Acidgullet
        t1 = '󱟂 Run Out Acid',
        t2 = '5y radius, 8s debuff',
        t3 = '',
        color = c.o,
        symbol = s.getout,
        debug = '325418',
    },
    [164517] = { --Tred'ova BOSS
        t1 = "󰎔 Coalescing Poison: ㄫ Pull in, ぁ 20y",
        t2 = '󰴽 Spread, Dodge never same way twice',
        t3 = '󰠬 Kick rot: Pac, Inc, Dom, 󰆸 Kite adds, 󰓡 Break beam',
        color = c.g,
        symbol = s.spread,
        debug = '463602, 322655, 337235, 337251, 337253',
    },

    -- Siege of Boralus

    [141283] = { -- Kul Tiran Halberd
        t1 = s.run .. ' Knocker: 2s cast, 10y knock',
        t2 = s.spread .. ' Sidestep during cast',
        t3 = '',
        color = c.y,
        symbol = s.getout,
        debug = '256627',
    },
    [141565] = { -- Kul Tiran Footman
        t1 = s.tankwarn .. ' Hindering Cut',
        t2 = s.heal .. ' 35% haste reduction',
        t3 = '',
        color = c.o,
        symbol = s.tankwarn,
        debug = '273930',
    },
    [141284] = { -- Kul Tiran Wavetender
        t1 = s.kick .. ' Kick Shell or Purge',
        t2 = s.tankwarn .. ' 90% dmg red, explodes @ 10s',
        t3 = s.rng .. ' Bolt random tgt nature dmg',
        color = c.y,
        symbol = s.kick,
        debug = '256957',
    },
    [132532] = { -- Kul Tiran Marksman
        t1 = s.rng .. ' Molten Slug fire dmg',
        t2 = s.heal .. ' Heal through',
        t3 = '',
        color = c.g,
        symbol = s.heal,
        debug = '257641',
    },
    [132481] = { -- Kul Tiran Vanguard
        t1 = s.turnmob .. ' Tank facing away',
        t2 = s.spread .. ' Heavy Slash 4s stun',
        t3 = '  Directional',
        color = c.y,
        symbol = s.tankwarn,
        debug = '257292',
    },
    [144158] = { -- Sergeant Bainbridge BOSS
        t1 = s.bomb .. ' Kite boss into Ordinance = 6s Burn',
        t2 = s.run .. ' 20s fixate, +5% spd ev 2s',
        t3 = s.target .. ' Focus adds',
        color = c.p,
        symbol = s.tankwarn,
        debug = '',
    },
    [144160] = { -- Chopper Redhook BOSS - SAME
        t1 = s.bomb .. ' Kite boss into Ordinance = 6s Burn',
        t2 = s.run .. ' 20s fixate, +5% spd ev 2s',
        t3 = s.target .. ' Focus adds',
        color = c.p,
        symbol = s.tankwarn,
        debug = '',
    },
    [144071] = { -- Kul Tiran Waveshaper
        t1 = s.kick .. ' Kick Shell or Purge',
        t2 = s.tankwarn .. ' 90% dmg red, explodes @ 10s',
        t3 = s.rng .. ' Bolt random tgt nature dmg',
        color = c.y,
        symbol = s.kick,
        debug = '256957',
    },
    [138254] = { -- Kul Tiran Powdershot
        t1 = s.rng .. ' Molten Slug fire dmg',
        t2 = s.heal .. ' Heal through',
        t3 = '',
        color = c.g,
        symbol = s.heal,
        debug = '257641',
    },
    [129373] = { -- Dockhound Packmaster
        t1 = s.focus .. ' Kill Fast',
        t2 = s.bubble .. ' +125% dmg buff',
        t3 = s.spread .. ' Dodge Charge if not target',
        color = c.o,
        symbol = s.one,
        debug = '',
    },
    [129640] = { -- Snarling Dockhound
        t1 = s.kick .. ' Clamping Jaws: 10s Root',
        t2 = '',
        t3 = '',
        color = c.y,
        symbol = s.kick,
        debug = '',
    },

}

