function (modTable)
    modTable.cache = {}
    modTable.prefs = {
        w = 192,
        h = 48,
        scale = 1.0,
        path = [[Interface\AddOns\ctrl\assets\bar\]],
        fnt = {
            med = [[Interface\AddOns\SharedMedia_Singletail\font\Prompt-Bold.ttf]],
            reg = [[Interface\AddOns\SharedMedia_Singletail\font\Prompt-Medium.ttf]],
            mono = [[Interface\AddOns\SharedMedia_Singletail\font\Hack-Medium.ttf]],
            pro = [[Interface\AddOns\SharedMedia_Singletail\font\ProFontWindows-Regular.ttf]],
            term = [[Interface\AddOns\SharedMedia_Singletail\font\Terminus(TTF)-Bold.ttf]],
        },
        rgba = {
            red = { 0.75, 0.0, 0.0, 1, },
            green = { 0.0, 0.5, 0.0, 1, },
            blue = { 0.0, 0.0, 0.5, 1, },
            yellow = { 0.5, 0.5, 0.0, 1, },
            purple = { 0.5, 0.0, 0.5, 1, },
            cyan = { 0.0, 0.5, 0.5, 1, },
            orange = { 1.0, 0.5, 0.0, 1, },
            white = { 0.5, 0.5, 0.5, 1, },
            gray = { 0.5, 0.5, 0.5, 1, },
            pink = { 1, 0.0, 0.85, 1, },
        },
        hex = {
            w = [[|cffffffff]],
            a = [[|cff777777]],
            r = [[|cffff2e38]],
            o = [[|cffffb836]],
            y = [[|cfffff000]],
            g = [[|cff24cf19]],
            b = [[|cff4975ff]],
            v = [[|cffd649ff]],
            c = [[|cff5bcefa]],
            p = [[|cfff563af]],
            gray = [[|cff888888]],
            hunter = [[|cffabd473]],
            brown = [[|cff8d5000]],
            warlock = [[|cff999ff3]],
            evoker = [[|cff8788ee]],
        },
        reaction = {
            [0] = { 0.5, 0.5, 0.5, 0.5, }, --gray
            [1] = { 0.75, 0.0, 0.0, 0.5, }, --hated
            [2] = { 1.0, 0.0, 0.0, 0.5, },
            [3] = { 1.0, 0.5, 0.0, 0.5, },
            [4] = { 1.0, 1.0, 0.0, 0.5, },
            [5] = { 0.0, 1.0, 0.0, 0.5, },
            [6] = { 0.0, 1.0, 0.33, 0.5, },
            [7] = { 0.0, 1.0, 0.66, 0.5, },
            [8] = { 0.0, 1.0, 1.0, 0.5, }, --exalted
        },
        alpha = {
            ['boss']      = 1.0,
            ['worldboss'] = 1.0,
            ['rareelite'] = 0.8,
            ['elite']     = 0.7,
            ['rare']      = 0.6,
            ['normal']    = 0.3,
            ['trivial']   = 0.2,
            ['minus']     = 0.1,
        },
        icon = {
            ['?']         = 'よ',
            ['!']         = 'も',
            ['boss']      = 'ぢ',
            ['worldboss'] = '【',
            ['rareelite'] = '䆓',
            ['elite']     = '䅈',
            ['rare']      = '㎙',
            ['normal']    = '㌤',
            ['trivial']   = '󱔎',
            ['minus']     = '䅶',
            ['no']        = 'ォ',
            ['kick']      = '㏅',
            ['dick']      = '㏤',
            ['butt']      = '㏙',
            ['TANK']      = '㍵',
            ['HEALER']    = '㎈',
            ['DAMAGER']   = '㌤',
            ['NONE']      = 'ォ',
            ['CC']        = '㇂',
            ['nil']       = '␀',
            ['anal']      = '㐃',
            ['lips']      = '㎺',
            ['candle']    = '㍐',
            ['aoe']       = '㍘',
            ['boobs']     = '㏓',
            ['bot']       = '】',
            ['event']     = 'う',
            ['friend']    = '㊅',
            ['enemy']     = '㌤',
            ['random']    = '㌗',
            ['horde']     = '㌡',
            ['tankwarn']  = '㎂',
            ['dress']     = '㏄',
            ['PALADIN']   = '㌰',
            ['PRIEST']    = '㌲',
            ['HUNTER']    = '㌴',
            ['MAGE'] = '㌶',
            ['DRIUD'] = '㌸',
            ['DEMONHUNTER'] = '㌺',
            ['WARRIOR'] = '㍀',
            ['ROGUE'] = '㍂',
            ['SHAMAN'] = '㍄',
            ['WARLOCK'] = '㍆',
            ['EVOKER'] = '䂛',
            ['MONK'] = '䃱',
            ['DEATHKNIGHT'] = 'っ',
        },
        threat = {
            [0] = '-',
            [1] = '+',
            [2] = 'WARN',
            [3] = 'AGGRO',
        }
    }

    modTable.elements = {
        frame = {
            ['base'] = {fl = 0, w = modTable.prefs.w, h = modTable.prefs.h, x=-10, y=14, pa='BOTTOMLEFT'},
            ['top'] = {target = 'base', fl = 300, w=modTable.prefs.w, h = modTable.prefs.h, x=0, y=0},
        },
        bar = {
            ['threat'] = {target = 'base'},
        },
        texture = {
            ['shadow'] = {file = 'blacc', x = -3, y = 6, target = 'base', alpha= 1, layer = -6,},
            ['frame'] = {file = 'thinn', x = -3, y = 6, target = 'base', layer = 0,},
            ['cback'] = {file = 'cback', x = 3, y = 3, target = 'base', w = 44, h = 44, a = 'TOPRIGHT', alpha = 1, layer = -6,},
            ['circle'] = {file = 'cirque', x = 3, y = 3, target = 'base', w = 44, h = 44, a = 'TOPRIGHT', layer = 0,},
            ['error'] = {file = 'checkengine40', x = 1, y = 1, w = 36, h = 36, a = 'TOPRIGHT', t = 'base', l = -3},
        },
        fontString = {
            ['icon'] = { t = 'ォ', x=-52, y=15, fnt = modTable.prefs.fnt.med, fs = 24, jh = 'CENTER', jv = 'MIDDLE', w=48, h=48},
            ['note'] = { x = 2, y = -2, fnt = modTable.prefs.fnt.reg, fs = 10, jh = 'LEFT', jv = 'MIDDLE'},
            ['info'] = { x = 2, y = -12, fnt = modTable.prefs.fnt.reg, fs = 10, jh = 'LEFT', jv = 'MIDDLE'},
            ['debug'] = { x = 2, y = -24, fnt = modTable.prefs.fnt.mono, fs = 10, jh = 'LEFT', jv = 'MIDDLE'},
            ['debug2'] = { x = 2, y = -36, fnt = modTable.prefs.fnt.mono, fs = 10, jh = 'LEFT', jv = 'MIDDLE'},
            ['id'] = { x = -52, y = 14, w = 48, h = 12, fnt = modTable.prefs.fnt.pro, fs = 12, jh = 'CENTER', jv = 'TOP'},        
            ['npcId'] = { x = -52, y = -27, w = 48, h = 12, fnt = modTable.prefs.fnt.med, fs = 9, jh = 'CENTER', jv = 'TOP'},
        },
    }

    modTable.prefs.guild = {
        ["The Immortal Taint"]  = { '䀈', 'p' },
        ["Tainted Angels"]      = { '㌦', 'c' },
        ["Taintcraft"]          = { '䂭', 'o' },
        ["Power Word Taint"]    = { '㍋', 'o' },
        ["War Taint"]           = { '㎆', 'v' },
        ["The Spreading Taint"] = { '㏛', 'o' },
        ["Taint"]               = { '㏠', 'v' },
        ["Bear Taint"]          = { '󱙵', 'v' },
        ["Tainter Tots"]        = { '󱜚', 'v' },
        ["Tainted Love"]        = { '㎡', 'v' },
        ["Taint of Madness"]    = { '䅡', 'v' },
        ["Taint No Thang"]      = { '〡', 'v' },
        ["Spreading Taint"]     = { '㐃', 'v' },
    }
end