function (modTable)
    modTable.cache = {}
    modTable.prefs = {
        w = 224,
        h = 32,
        scale = 1.0,
        path = [[Interface\AddOns\ctrl\assets\plater\]],
        fnt = {
            bold = [[Interface\AddOns\ctrl\assets\fnt\full\Prompt-Bold.ttf]],
            med = [[Interface\AddOns\ctrl\assets\fnt\full\Prompt-Medium.ttf]],
            reg = [[Interface\AddOns\ctrl\assets\fnt\full\Prompt-Regular.ttf]],
            mono = [[Interface\AddOns\ctrl\assets\fnt\full\ProFontWindows-Regular.ttf]],
        },
        rgba = {
            red = { 0.5, 0.0, 0.0, 0.5, },
            green = { 0.0, 0.5, 0.0, 1, },
            blue = { 0.0, 0.0, 0.5, 1, },
            yellow = { 0.5, 0.5, 0.0, 1, },
            purple = { 0.5, 0.0, 0.5, 1, },
            cyan = { 0.0, 0.5, 0.5, 1, },
            orange = { 1.0, 0.5, 0.0, 1, },
            white = { 0.5, 0.5, 0.5, 1, },
            gray = { 0.5, 0.5, 0.5, 1, },
            pink = { 1, 0.0, 0.85, 1, },
            DEATHKNIGHT = { 0.38, 0.06, 0.11, 1, },
            DEMONHUNTER = { 0.32, 0.9, 0.4, 1, },
            DRUID = { 0.5, 0.25, 0.02, 1, },
            HUNTER = { 0.33, 0.41, 0.22, 1, },
            MAGE = { 0.2, 0.4, 0.46, 1, },
            MONK = { 0.0, 0.5, 0.28, 1, },
            PALADIN = { 0.46, 0.27, 0.36, 1, },
            PRIEST = { 0.5, 0.5, 0.5, 1, },
            ROGUE = { 0.5, 0.48, 0.2, 1, },
            SHAMAN = { 0.0, 0.22, 0.43, 1, },
            WARLOCK = { 0.27, 0.25, 0.4, 1, },
            WARRIOR = { 0.39, 0.3, 0.21, 1, },
        },
        hex = {
            w = [[|cffffffff]],
            a = [[|cff777777]],
            r = [[|cffff2e38]],
            o = [[|cffffb836]],
            y = [[|cfffff000]],
            g = [[|cff24cf19]],
            b = [[|cff4975ff]],
            v = [[|cffd649ff]],
            c = [[|cff5bcefa]],
            p = [[|cfff563af]],
            gray = [[|cff888888]],
            hunter = [[|cffabd473]],
            brown = [[|cff8d5000]],
            warlock = [[|cff999ff3]],
            evoker = [[|cff8788ee]],
        },
        reaction = {
            [0] = { 0.5, 0.5, 0.5, 0.5, }, --gray
            [1] = { 0.75, 0.0, 0.0, 0.5, }, --hated
            [2] = { 1.0, 0.0, 0.0, 0.5, },
            [3] = { 1.0, 0.5, 0.0, 0.5, },
            [4] = { 1.0, 1.0, 0.0, 0.5, },
            [5] = { 0.0, 1.0, 0.0, 0.5, },
            [6] = { 0.0, 1.0, 0.33, 0.5, },
            [7] = { 0.0, 1.0, 0.66, 0.5, },
            [8] = { 0.0, 1.0, 1.0, 0.5, }, --exalted
        },
        enemy = {
            ['boss'] = { 0.5, 0, 0, 0.5, },
            ['worldboss'] = { 0.5, 0.0, 0.0, 0.5, },
            ['rareelite'] = { 0.45, 0.0, 0.0, 0.5, },
            ['elite'] = { 0.4, 0.0, 0.0, 0.5, },
            ['rare'] = { 0.35, 0.0, 0.0, 0.5, },
            ['normal'] = { 0.3, 0.0, 0.0, 0.5, },
            ['trivial'] = { 0.25, 0.0, 0.0, 0.5, },
            ['minus'] = { 0.2, 0.0, 0.0, 0.5, },
        },
        alpha = {
            ['boss']      = 1.0,
            ['worldboss'] = 1.0,
            ['rareelite'] = 0.8,
            ['elite']     = 0.7,
            ['rare']      = 0.6,
            ['normal']    = 0.3,
            ['trivial']   = 0.2,
            ['minus']     = 0.1,
        },
        icon = {
            ['?']         = 'よ',
            ['!']         = 'も',
            ['boss']      = 'ぢ',
            ['worldboss'] = '【',
            ['rareelite'] = '䆓',
            ['elite']     = '䅈',
            ['rare']      = '㎙',
            ['normal']    = '㌤',
            ['trivial']   = '󱔎',
            ['minus']     = '䅶',
            ['no']        = 'ォ',
            ['kick']      = '㏅',
            ['dick']      = '㏤',
            ['butt']      = '㏙',
            ['TANK']      = '㍵',
            ['HEALER']    = '㎈',
            ['DAMAGER']   = '㌤',
            ['NONE']      = 'ォ',
            ['CC']        = '㇂',
            ['nil']       = '␀',
            ['anal']      = '㐃',
            ['lips']      = '㎺',
            ['candle']    = '㍐',
            ['aoe']       = '㍘',
            ['boobs']     = '㏓',
            ['bot']       = '】',
            ['event']     = 'う',
            ['friend']    = '㊅',
            ['enemy']     = '㌤',
            ['random']    = '㌗',
            ['horde']     = '㌡',
            ['tankwarn']  = '㎂',
            ['dress']     = '㏄',
            ['PALADIN']   = '㌰',
            ['PRIEST']    = '㌲',
            ['HUNTER']    = '㌴',
            ['MAGE'] = '㌶',
            ['DRIUD'] = '㌸',
            ['DEMONHUNTER'] = '㌺',
            ['WARRIOR'] = '㍀',
            ['ROGUE'] = '㍂',
            ['SHAMAN'] = '㍄',
            ['WARLOCK'] = '㍆',
            ['EVOKER'] = '䂛',
            ['MONK'] = '䃱',
            ['DEATHKNIGHT'] = 'っ',
        },
        threat = {
            [0] = '-',
            [1] = '+',
            [2] = 'WARN',
            [3] = 'AGGRO',
        }
    }

    modTable.prefs.barw = (modTable.prefs.w - modTable.prefs.h) / 100

    modTable.elements = {
        frame = {
            ['base'] = {fl=0, w=modTable.prefs.w, h=modTable.prefs.h, x=0, y=0, a='TOPLEFT', pa='TOPLEFT'},
            ['top'] = {target='base', fl=300, w=modTable.prefs.w, h=modTable.prefs.h, x=0, y=0, a='TOPLEFT', pa='TOPLEFT'},
        },
        --bar = {
        --    ['threat'] = {target = 'base'},
        --},
        texture = {
            ['bk'] = {file='np_bk.png', target='base', alpha=1, layer=-6,},
            ['cap'] = {file='cap64.png', x=0, y=0, w=modTable.prefs.h, h=modTable.prefs.h, alpha=0.5, target='base', layer=-5,},
            ['hbar'] = {file='bar.png', x=modTable.prefs.h, y=0, target='base', w=modTable.prefs.w-modTable.prefs.h, h=modTable.prefs.h, alpha=0.5, layer=-5,},
            ['shadow'] = {file='np_s.png', target='base', alpha=1, layer=-4,},
            ['box'] = {file='np.box.png', t='base', alpha=1, layer=-3},
            ['box2'] = {file='np.box.png', t='base', alpha=1, layer=-2},
        },
        fontString = {
            ['icon'] = { t='ォ', x=2, y=-2, fnt=modTable.prefs.fnt.med, fs=21, jh='CENTER', jv ='MIDDLE', w=modTable.prefs.h, h=modTable.prefs.h, alpha=0.8},
            ['name'] = { x=modTable.prefs.h, y=-3, fnt=modTable.prefs.fnt.med, fs=10, jh='LEFT', jv='TOP', alpha=1, a='TOPLEFT', pa='TOPLEFT'},
            ['note'] = { x=modTable.prefs.h, y=-12, fnt=modTable.prefs.fnt.reg, fs=10, jh='LEFT', jv='TOP', alpha=0.8},
            ['info'] = { x=modTable.prefs.h, y=-21, fnt=modTable.prefs.fnt.reg, fs=10, jh='LEFT', jv='TOP', alpha=0.8},
            ['health'] = { t='100%', x=-3, y=-1, fnt=modTable.prefs.fnt.med, fs=10, jh='RIGHT', jv='TOP', a='TOPRIGHT', pa='TOPRIGHT', alpha=0.8},
            ['hpm'] = { t='', x=-3, y=-12, fnt=modTable.prefs.fnt.reg, fs=10, jh='RIGHT', jv='TOP', a='TOPRIGHT', pa='TOPRIGHT', alpha=0.8},
            ['target'] = { t='target', x=-3, y=-21, fnt=modTable.prefs.fnt.reg, fs=10, jh='RIGHT', jv='TOP', a='TOPRIGHT', pa='TOPRIGHT', alpha=0.8},
            ['debug'] = { x = 10, y = -30, fnt = modTable.prefs.fnt.mono, fs=10, jh = 'LEFT', jv = 'TOP', alpha=0.8},
            ['debug2'] = { x = 10, y = -40, fnt = modTable.prefs.fnt.mono, fs=10, jh = 'LEFT', jv = 'TOP', alpha=0.8},
        },
    }
    
    modTable.prefs.guild = {
        ["The Immortal Taint"]  = { '䀈', 'p' },
        ["Tainted Angels"]      = { '㌦', 'c' },
        ["Taintcraft"]          = { '䂭', 'o' },
        ["Power Word Taint"]    = { '㍋', 'o' },
        ["War Taint"]           = { '㎆', 'v' },
        ["The Spreading Taint"] = { '㏛', 'o' },
        ["Taint"]               = { '㏠', 'v' },
        ["Bear Taint"]          = { '󱙵', 'v' },
        ["Tainter Tots"]        = { '󱜚', 'v' },
        ["Tainted Love"]        = { '㎡', 'v' },
        ["Taint of Madness"]    = { '䅡', 'v' },
        ["Taint No Thang"]      = { '〡', 'v' },
        ["Spreading Taint"]     = { '㐃', 'v' },
    }
end

