--[[ ctrl - symbols.lua - t@wse.nyc - 17 July 2025 ]] --

---@class ctrl
local ctrl = select(2, ...)

ctrl.s = {
    ['ctrl']       = '、',
    ['console']    = 'べ',
    ['power']      = '　',
    ['evt']        = 'う',
    ['nul']        = '␀',
    ['bug']        = '〡',
    ['crit']       = '㎙',
    ['save']       = 'バ',
    ['info']       = 'め',
    ['i']          = 'む',
    ['emerg']      = '㎛',
    ['alert']      = 'と',
    ['notice']     = 'ベ',
    ['keyboard']   = 'せ',
    ['?']          = 'よ',
    ['secure']     = '㉔',
    ['insecure']   = '㉕',
    ['taint']      = '㉕',
    ['db']         = '㊘',
    ['check']      = 'を',
    ['8ball']      = '󰭡',
    ['clippy']     = '〓',
    ['lua']        = '㈰',
    ['code']       = '',
    ['lockdown']   = '󰳌',
    ['safe']       = '󰳈',
    ['tx']         = '',
    ['frame']      = '㇁',
    ['ux']         = 'ぅ',
    ['btns']       = '㇠',
    ['template']   = '󰋯',
    ['sys']        = '󰍛',
    ['sfx']        = '㇦',
    ['cleu']       = 'す',
    ['bow']        = '㍣',
    ['cvar']       = '〲',
    ['cvar_alert'] = '〶',
    ['zoomIn']     = 'ド',
    ['zoomOut']    = 'ニ',
    ['min']        = '󰘕', -- '䔦',
    ['max']        = '󰘖', --  '䔥',
    ['TANK']       = '㍵',
    ['HEALER']     = '㎈',
    ['DAMAGER']    = '㌤',
    ['NONE']       = 'ォ',
    ['aura']       = '㍋',

    ['skull']          = 'ぢ',
    ['dinosaur']       = '【',
    ['snek']           = '󱔎',
    
    ['spider']         = '󱇫',
    ['bunny']          = '䅶',
    ['shark']          = '䆓',
    ['king']           = '󱟝',
    ['crown']          = '䅴',
    ['nuclear']        = 'つ',
    ['fallout']        = 'づ',
    ['nuke']           = '䂺',
    ['fist']           = '㎻',
    ['truck']          = '󱊝',
    ['poop']           = '䇘',
    ['frost']          = '',
    ['pirate']         = '󰨈',
    ['sparkle']        = '󰙴',
    ['heart'] = '㎠',

    ['kick']           = '㏅',
    ['kick2']          = '㏆',
    ['roundhouse']     = '󰠬',
    ['cc']             = '㇂',
    ['target']         = '㎘',
    ['tag']            = '󱈤',
    ['new']            = '󰎔',
    ['pro']            = '󰐭',
    ['bio']            = '󰂦',
    ['bleed']          = '䂩',
    ['wipe']           = '󰫩',
    ['sleep']          = '󰋣',
    ['command']        = '、',
    ['taunt']          = '󰙊',

    ['no']             = 'ォ',
    ['x']              = '󰛉',
    ['hand']           = '󰩏',
    ['warn']           = 'と',
    ['question']       = 'よ',
    ['plus']           = '󰐙',
    ['show']           = 'ゲ',
    ['hide']           = 'コ',
    ['location']       = 'ㄕ',
    ['ping']           = 'ㄉ',
    ['megaphone']      = '',
    ['exclamation']    = '󰳧',
    ['shout']          = '󱋉',
    ['focus']          = '󰯐',
    ['unknowntarget']  = '󱄶',
    ['desync']         = '󰌺',

    ['ghost']          = '〠',
    ['dontrelease']    = '󱙜',
    ['bomb']           = '㍩',
    ['biohazard']      = 'て',
    ['fire']           = 'で',
    ['angel']          = '㌦',
    ['ankh']           = '䀈',
    ['bubble']         = '㍊',
    ['priest']         = '䁨',
    ['egg']            = '䂭',
    ['dead']           = '䂹',
    ['stop']           = '䃯',
    ['armor']          = '㍱',
    ['squid']          = '䅐',
    ['blink']          = '䅧',

    ['pacman']         = '󰮯',
    ['cake']           = '󰃫',
    ['flask']          = '󰂖',
    ['mushroom']       = '󰟟',
    ['syringe']        = '䊩',

    ['anus']           = '〤',
    ['trans']          = '󰊟',
    ['boobs']          = '㏓',
    ['tits']           = '㏔',
    ['butt']           = '㏙',
    ['ass']            = '㏚',
    ['jockstrap']      = '㏛',
    ['flyingpenis']    = '㏠',
    ['dick']           = '㏤',
    ['cock']           = '㏥',
    ['vag']            = '㏦',
    ['panties']        = '㏕',
    ['bdsm']           = '㎰',
    ['crop']           = '㎶',
    ['vibe']           = '㏱',
    ['buttplug']       = '㏵',
    ['threesome']      = '㐅',
    ['spank']          = '㐇',
    ['anal']           = '㐉',
    ['gag'] = '㎱',
    ['fear'] = '㎖',
    ['whip']           = '㐩',
    ['singletail']     = '㐪',

    ['reflect']        = '㎆',
    ['spread']         = '󰁌',
    ['stayclose']      = '㎷',
    ['collapse']       = 'ㄫ',
    ['swap']           = '󰒟',
    ['spin']           = '󰹻',
    ['getin']          = '󰿄',
    ['getout']         = '󰿅',
    ['jump']           = '󰘲',
    ['separate']       = '󰓡',
    ['venn']           = '󰝾',
    ['serpentine']     = '󰴽',

    ['backleft']       = '󰦷',
    ['backright']      = '󰦹',
    ['back']           = '󰦿',
    ['leftward']       = '󰧀',
    ['rightward']      = '󰧂',
    ['frontleft']      = '󰧃',
    ['frontright']     = '󰧅',
    ['forward']        = '󰧇',
    ['left']           = 'ㅀ',
    ['right']          = 'ㅁ',
    ['up']             = 'ㅂ',
    ['down']           = 'ㅃ',

    ['turnaround']     = '󱞮',
    ['turnleft']       = '󱞨',
    ['turnright']      = '󱞬',
    ['pullforward']    = '󰆸',
    ['pullback']       = '󰆹',
    ['pullleft']       = '󰑁',
    ['pullright']      = '󰑃',
    ['turnmob']        = '󰆷',
    ['point']          = '󰋇',

    ['run']            = 'ぁ',
    ['move']           = '㎃',
    ['rotate']         = '䂈',
    ['branch']         = '㈧',
    ['throughdoor']    = '󰩈',
    ['squeezepast']    = '󱇖',
    ['groupup']        = '󱇢',
    ['upstairs']       = '󱊽',
    ['downstairs']     = '󱊾',
    ['puddle']         = '󱟂',

    ['fly']            = '󰀝',
    ['swim']           = '󱢺',
    ['go']             = '㈋',
    ['mount']          = '󱗀',
    ['fan']            = '󰫖',
    ['sixfeet']        = '㎗',
    ['enrage']         = '䅈',
    ['imposter']       = '㎙',

    ['tank']           = '㍵',
    ['offtank']        = '㍹',
    ['shield']         = '󰒘',
    ['tankwarn']       = '㎂',
    ['donttank']       = '󰦜',
    ['tankfly']        = '󰚻',
    ['tankstar']       = '󱄼',
    ['chaintank']      = '󰴴',
    ['bugtank']        = '󱏛',
    ['tankboss']       = '󱢽',
    ['tankmelee']      = '󱢿',
    ['tankbuster']     = '䁊',

    ['melee']          = '㍨',
    ['combat']         = '㍡',
    ['wand']           = '󰁨',
    ['ranged']         = '󱡁',
    ['heal']           = '㎉',
    ['group']          = '㌩',

    ['zero']           = '㊰',
    ['one']            = '㊱',
    ['two']            = '㊲',
    ['three']          = '㊳',
    ['four']           = '㊴',
    ['five']           = '㊵',
    ['six']            = '㊶',
    ['seven']          = '㊷',
    ['eight']          = '㊸',
    ['nine']           = '㊹',
    ['ten']            = '󰿭',

    ['d20']            = '㌗',
    ['eightball']      = '󰭡',
    ['random']         = '㌖',
    ['dice']           = '󱅖',
    ['rng']            = '󱄔',
    ['onetwothree']    = '󰎠',
    ['tenseconds']     = '󰔜',
    ['threeseconds']   = '󰔝',
    ['percentage']     = '󱨅',
    ['percentagewarn'] = '󱨆',

    ['log']            = '󱂅',
    ['api']            = '󱂛',
    ['action']         = '󰿎',
    ['strength']       = '󱅝',
    ['ok']             = 'い',
    ['infinite']       = '󰚾',

    ['horde']          = '㌡',
    ['alliance']       = '㏦',

    ['PALADIN']     = '㌰',
    ['PRIEST']      = '㌲',
    ['HUNTER']      = '㌴',
    ['MAGE']        = '㌶',
    ['DRIUD']       = '㌸',
    ['DEMONHUNTER'] = '㌺',
    ['WARRIOR']     = '㍀',
    ['ROGUE']       = '㍂',
    ['SHAMAN']      = '㍄',
    ['WARLOCK']     = '㍆',
    ['EVOKER']      = '䂛',
    ['MONK']        = '䃱',
    ['DEATHKNIGHT'] = '㌢',

    ["The Immortal Taint"]  = '䀈',
    ["Tainted Angels"]      = '㌦',
    ["Taintcraft"]          = '䂭',
    ["Power Word Taint"]    = '㍋',
    ["War Taint"]           = '㎆',
    ["Taint of the Titans"] = '㏛',
    ["Taint"]               = '㏠',
    ["Bear Taint"]          = '󱙵',
    ["Tainter Tots"]        = '󱜚',
    ["Tainted Love"]        = '㎡',
    ["Taint of Madness"]    = '䅡',
    ["Taint No Thang"]      = '〡',
    ["Spreading Taint"]     = '㐃',

    ["Player-5-0AA78045"] = '㐪', --Singltail
}

-- 㐪 ㌡ ㌢ 䖿 䃿 䄃 ㏦ ㏧ ㍉ ㍊ 〧 〨 〖 ㏘ ㎛ 䃜 䄚 䣯 䣰


ctrl.s.ghosts = ctrl.c.d
for i = 1, 4 do
    ctrl.s.ghosts = ctrl.c.pm[i] .. ctrl.s.ghost .. ctrl.s.ghosts
end

